# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0b34515ed7652bcfd2af389c7602572f3d8f148ae8cb28c8f908902e43a125d6ce39fb4b25d3c2997cef06d1d2e50409d756b04616092b7640142171a307efe

test:
  secret_key_base: 6138cc60fda4b120df37c3d341e00288722a50c638586d934f2997c54c643ea1cf8a243f9de47a212cea293c458d113996049f78567fb00da8a09262a88ec7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
